version: '3.3'

services:
  remo-exporter:
    ports:
      - 9352:9352
    image: kenfdev/remo-exporter:latest
    environment:
      OAUTH_TOKEN_FILE: '/run/secrets/api-keys'
    secrets:
      - api-keys
  prom:
    image: quay.io/prometheus/prometheus:v3.15.0
    volumes:
      - ./prometheus.sample.yml:/etc/prometheus/prometheus.yml
    command: '--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    depends_on:
      - remo-exporter
  grafana:
    image: grafana/grafana:13.2.3
    ports:
      - '3000:3000'
    depends_on:
      - prom

secrets:
  api-keys:
    file: ./api-keys
