// Code generated by MockGen. DO NOT EDIT.
// Source: ./http/authhttp.go
//
// Generated by this command:
//
//	mockgen -source ./http/authhttp.go -destination ./mocks/authhttp.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthHttpDoer is a mock of AuthHttpDoer interface.
type MockAuthHttpDoer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHttpDoerMockRecorder
	isgomock struct{}
}

// MockAuthHttpDoerMockRecorder is the mock recorder for MockAuthHttpDoer.
type MockAuthHttpDoerMockRecorder struct {
	mock *MockAuthHttpDoer
}

// NewMockAuthHttpDoer creates a new mock instance.
func NewMockAuthHttpDoer(ctrl *gomock.Controller) *MockAuthHttpDoer {
	mock := &MockAuthHttpDoer{ctrl: ctrl}
	mock.recorder = &MockAuthHttpDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHttpDoer) EXPECT() *MockAuthHttpDoerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAuthHttpDoer) Get(url string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", url)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAuthHttpDoerMockRecorder) Get(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAuthHttpDoer)(nil).Get), url)
}
