// Code generated by MockGen. DO NOT EDIT.
// Source: ./exporter/remo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/kenfdev/remo-exporter/types"
)

// MockRemoGatherer is a mock of RemoGatherer interface
type MockRemoGatherer struct {
	ctrl     *gomock.Controller
	recorder *MockRemoGathererMockRecorder
}

// MockRemoGathererMockRecorder is the mock recorder for MockRemoGatherer
type MockRemoGathererMockRecorder struct {
	mock *MockRemoGatherer
}

// NewMockRemoGatherer creates a new mock instance
func NewMockRemoGatherer(ctrl *gomock.Controller) *MockRemoGatherer {
	mock := &MockRemoGatherer{ctrl: ctrl}
	mock.recorder = &MockRemoGathererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRemoGatherer) EXPECT() *MockRemoGathererMockRecorder {
	return m.recorder
}

// GetDevices mocks base method
func (m *MockRemoGatherer) GetDevices() (*types.GetDevicesResult, error) {
	ret := m.ctrl.Call(m, "GetDevices")
	ret0, _ := ret[0].(*types.GetDevicesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppliances mocks base method
func (m *MockRemoGatherer) GetAppliances() (*types.GetAppliancesResult, error) {
	ret := m.ctrl.Call(m, "GetAppliances")
	ret0, _ := ret[0].(*types.GetAppliancesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices
func (mr *MockRemoGathererMockRecorder) GetDevices() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockRemoGatherer)(nil).GetDevices))
}

// GetAppliances indicates an expected call of GetAppliances
func (mr *MockRemoGathererMockRecorder) GetAppliances() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppliances", reflect.TypeOf((*MockRemoGatherer)(nil).GetAppliances))
}
