apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: remo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:5.4.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
