kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  namespace: remo
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    # rule_files:
    #     - 'alert.rules.yml'
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: "remo"
        scrape_interval: 60s
        dns_sd_configs:
          - names: ['remo-exporter.remo']
            port: 9352
            type: A
            refresh_interval: 5s
    # alerting:
    #   alertmanagers:
    #   - static_configs:
    #     - targets:
    #       - alertmanager.remo:9093
