apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: remo
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 31119
  selector:
    app: prometheus
