apiVersion: v1
kind: Service
metadata:
  name: remo-exporter
  namespace: remo
  labels:
    app: remo-exporter
spec:
  type: NodePort
  ports:
    - port: 9352
      protocol: TCP
      targetPort: 9352
      nodePort: 30352
  selector:
    app: remo-exporter
